repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        verbose: true
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        verbose: true
      - id: forbid-crlf # Forbid files containing CRLF end-lines to be committed
        verbose: true
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: system
        entry: stylua
        types: [lua]
        verbose: true
      - id: selene
        name: Selene
        language: system
        entry: selene
        files: ^lua/.*\.lua$
        types: [lua]
        verbose: true
      - id: run_tests
        name: Run Tests
        language: system
        entry: make test
        files: ^(lua|spec)/.*\.lua$
        types: [lua]
        verbose: true

# vim: set ts=2 sts=2 sw=2 et ai si sta:
