std = "vim" # Points to the `vim.yml` file

[lints]
global_usage       = "allow"
manual_table_clone = "allow"
mixed_table        = "allow"
unused_variable    = "allow"
# vim: set ts=4 sts=4 sw=4 et ai si sta:
