# StyLua configuration for code formatting
# Run with: stylua .

call_parentheses           = "Always"
collapse_simple_statement  = "Never"
column_width               = 120
indent_type                = "Spaces"
indent_width               = 2
line_endings               = "Unix"
quote_style                = "AutoPreferSingle"
space_after_function_names = "Never"
syntax                     = "LuaJIT"

[sort_requires]
enabled = false

# vim: set ts=4 sts=4 sw=4 et ai si sta:
