blank_issues_enabled: true
contact_links:
  - name: Have a question?
    url: https://github.com/gisketch/triforce.nvim/discussions
    about: Use GitHub Discussions instead

# vim: set ts=2 sts=2 sw=2 et ai si sta:
