name: panvimdoc
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/panvimdoc.yml
      - README.md
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: triforce
          pandoc: README.md
          version: "NVIM >=v0.9.0"
          toc: false
          demojify: true
          dedupsubheadings: true
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
